version: "3.9"

services:
  psql:
    image: postgres
    container_name: t3_bd_postgres_container
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - postgres_nw

  pgadmin:
    image: dpage/pgadmin4
    container_name: t3_bd_pgadmin_container
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - psql
    networks:
      - postgres_nw

networks:
  postgres_nw:
    driver: bridge
